### PR TITLE
Inheritance and derivation support

### PR DESCRIPTION
**Pull request by posborne**
This change moves to a dynamic model for resolving at runtime
derivation (derivedFrom) and inheritance (for specified keys).  This
is cleaner than the second-pass approach previously performed that
required additional funciton calls.

In addition, this commit adds a few missing attributes on fields,
registers, and peripherals.  Register arrays are now always populated
and the original register arrays are no longer present in the tree
(they are always expanded out).

### CODE REVIEW

**Comment by posborne** [comment]
@porkybrain @lizardo Please review to verify that this change fits your use cases and looks correct.  I built on top of the work @porkybrain but changed things up in order to avoid the second-pass and preferring performing lookups at runtime over writing over values at leaf nodes.

**Comment by lizardo** [comment]
I got this error:

> ...
>     parser = SVDParser.for_packaged_svd('Nordic', 'nrf51.svd')
>   File "/home/lizardo/virtualenv/tock/src/cmsis-svd/python/cmsis_svd/parser.py", line 83, in for_packaged_svd
>     pkg_resources.resource_filename("cmsis_svd", resource, remove_reserved))
> TypeError: resource_filename() takes exactly 3 arguments (4 given)

Shouldn't this line be `pkg_resources.resource_filename("cmsis_svd", resource), remove_reserved)` instead?

**Comment by lizardo** [comment]
After changing this line (supposing it was a typo), I noticed a few other issues:

* SVDPeripheral.interrupts is returning `None` instead of `[]` (this broke my script which assumes "interrupts" is always a list, as is on 0.2). To reproduce (compare with 0.2 output):
> python -c 'from cmsis_svd.parser import SVDParser; print [x.name for x in SVDParser.for_packaged_svd("Nordic", "nrf51.svd").get_device().peripherals if x.interrupts == []]'

* SVDRegister.dim is returning an infinite recursion. To reproduce:
> python -c 'from cmsis_svd.parser import SVDParser; print SVDParser.for_packaged_svd("Nordic", "nrf51.svd").get_device().peripherals[0].registers[0].dim'

**Comment by posborne** [comment]
> Shouldn't this line be pkg_resources.resource_filename("cmsis_svd", resource), remove_reserved) instead?

Yeah, something got thrown off at some point.  I'll fix that up in addition to the CI problems.

> SVDPeripheral.interrupts is returning None instead of [] (this broke my script which assumes "interrupts" is always a list, as is on 0.2). To reproduce (compare with 0.2 output):

Internally we need to differentiate between an empty list and not being present.  That being said, we can probably special-case list types to make the interface consistent (same goes for things like `registers`).

> SVDRegister.dim is returning an infinite recursion

`dim` is going away in favor of expanding out register arrays.  That being said, we should not be recursing infinitely.  There must be something wrong with my `__getattr__` implementation.  I'll check it out.

**Comment by posborne** [comment]
Some of these changes will are breaking compared with previous revisions, so we will be bumping to 0.3 once this is merged.

**Comment by lizardo** [comment]
One of my uses for cmsis-svd is to generate Rust structs from register definitions. Currently, I use the `dim` field to know how many positions to declare for that register, so I can generate something like:

> struct SomeReg {
> ...
> uint32_t someArray[N];
> ...
> }

where `N` is the number returned by `dim` (after validating `dim_increment` and `dim_index`). How would I be able generate such arrays in future versions (instead of `N` fields)?

**Comment by porkybrain** [comment]
I think dim in register context needs to stay in, I also use it to generate iteratable ranges of registers.

**Comment by posborne** [comment]
The problem is that the XML nodes for dim are not real registers -- I don't see a good way to keep the register array information as well as exposing the blown out nodes.  For new code, I think having all registers available "as they are" is probably easiest rather than having special array register nodes.

Would the following work:

* `SVDPeripheral.registers` always contains the full set of registers (not grouped)
* `SVDPeripheral.regster_arrays` contains the metadata you are interested in

We could probably also compute a property, `SVDPeripheral.registers_nonarray` that does not contain any of the array type ones.

P.S. This JSON file (used in the tests) is pretty handy for visualizing what is there currently.

https://raw.githubusercontent.com/posborne/cmsis-svd/inheritance-and-derivation-support/python/cmsis_svd/tests/MKL25Z4.json

**Comment by lizardo** [comment]
My suggestion would be something like (following your example):

> ...
> "register_arrays": [
>     {
>         "name": "FPROT%s",
>         "dim": 4,
>         "dim_increment": 0x1,
>         "dim_index": [3,2,1,0]
>     },
> ...

That would allow to reconstruct arrays using "registers" and "register_arrays".

**Comment by lizardo** [comment]
Also maybe a `"registers": ["FPROT3", "FPROT2", "FPROT1", "FPROT0"]` property inside `register_arrays` as well, but that can be easily reconstructed from `name` and `dim_index`.

**Comment by porkybrain** [comment]
I like the idea of expanding the registers and just providing an list of the names of the registers you expanded. That seems to me to be the most usable form and there isn't really any information loss.

**Comment by posborne** [comment]
Alright, I'll take a shot at that this evening.

**Pull request merged**
