### PR TITLE
Add GigaDevice gd32f0x, gd32f1x0 and gd32e23x svd.

### PR DESCRIPTION
**Pull request by grevaillot**
extracted from vendors's Keil support packs.

GigaDevice.GD32F1x0_DFP.3.1.0
GigaDevice.GD32F10x_DFP.2.0.1
GigaDevice.GD32E23x_DFP.1.0.0

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi @grevaillot you might want to include the license info for these SVD files as mentioned here:

https://github.com/posborne/cmsis-svd#license

**Comment by grevaillot** [comment]
> Hi @grevaillot you might want to include the license info for these SVD files as mentioned here:
> 
> https://github.com/posborne/cmsis-svd#license

ouch, indeed, and not obvious : gigadevice does mention any license, nor keil... I contacted them and update the PR if i manage to get an answer.

**Comment by posborne** [comment]
Thanks for the follow-up @deadprogram @grevaillot, will await license clarification.

**Comment by posborne** [comment]
Closed for now; please reopen if we get license clarification.

**Pull request closed without merging**
