### PR TITLE
Added latest Nordic SVD files, as of nRF5x-MDK-Pack 8.17.0

### PR DESCRIPTION
**Pull request by mariusmue**
Hi there,

For unrelated reasons, I downloaded the latest Nordic MDK pack today and realized, they added two SVD files not present here, and the existing two were modified.
Please find them enclosed in this PR.

Cheers.

### CODE REVIEW

**Comment by posborne** [comment]
Hi @mariusmue can you look into the failure in CI.   Passing CI is a requirement for changes to be incorporated; this could be an issue with the SVD files or the library (likely the library).

**Comment by mariusmue** [comment]
Hi @posborne - Sorry for the delay, I investigated the CI-failure.

The cause for it is the test script, rather than the library; it looks like the newer version of the nrf
It looks like the nrf51.svf file included in the nRF5x-MDK-Pack 8.17.0 does not contain peripheral description for 
- AMLI (AHB Multi-Layer Interface)
- SPIM1 (SPI master with easyDMA1)

What is your preferred strategy here: Going with the latest svd file and adjusting the test, or reverting to the old file for the nrf51, as it seems to be more complete?

**Comment by posborne** [comment]
@mariusmue Sorry about the delay in looking at this, got buried.

I would say that we should move to the newer definitions and update the tests for these definitions.  If this causes a problem for some users we can see about moving back and/or getting someone actively working with the chip to work with Nordic to try to resolve or answer questions about the differences.

**Comment by posborne** [comment]
Merging this, though quite a bit late.  I'll do a pass getting tests passing again against upstream.

**Pull request merged**
