### PR TITLE
Add SiFive FE310

### PR DESCRIPTION
**Pull request by aykevl**
This is a RISC-V chip. The SVD file has been copied from here:
https://github.com/AdaCore/svd2ada/blob/master/CMSIS-SVD/SiFive/FE310.svd

### CODE REVIEW

**Comment by posborne** [comment]
Hi @aykevl, certainly very interested in having this added to the collection.  In order to properly deal with licensing concerns, contributions here:

1. Should come directly from the siilicon vendor if possible.
2. Must include an explicit license associated with all files from the vendor and/or associated with each of the contributed SVD files.

I'm not terribly familiar with hifive or the overall RISC-V ecosystem so I'll defer to the rust-embeded RISC-V team for comments on sourcing available of SVD descriptions for common boards.  CC @bradjc @danc86 @dvc94ch @Disasm

**Comment by Disasm** [comment]
As far as I know, this FE310 SVD is not from vendor. I contacted the vendor twice about official SVDs and still no answer. I haven't seen any vendor SVDs for RISC-V chips so far.

**Comment by Disasm** [comment]
@aykevl Also consider looking at this one: https://github.com/riscv-rust/e310x/blob/master/e310x.svd, it may also contain some useful fixes.

**Comment by mbolivar** [comment]
@nategraff-sifive ^^ just FYI.

I use this repository's code from GDB and find it very convenient. Just something to consider.

**Comment by justinclift** [comment]
> I contacted the vendor twice about official SVDs and still no answer.

Which approaches have you tried? :smile:

[Their Forums](https://forums.sifive.com) are generally a decent place to get assistance, so asking there sounds like it would be reasonable.

Personally, I've seen decent responses from their forums, and/or contacting relevant people directly.

The "Contact Us" (now "Contact Sales") approach through their main website on the other hand... appears to be useless / unfit for purpose.  Never seen a response to anyone that's tried that. :frowning:

**Comment by Disasm** [comment]
@justinclift I tried contacting two different people by e-mail and also talked in person on RISC-V Symposium. Thanks for the hint, I'll try that.

**Comment by aykevl** [comment]
The closest I could find to an official SVD file is this:
https://www.npmjs.com/package/@sifive/devices
which links to:
https://github.com/micro-os-plus/sifive-devices-xpack
which includes this XSVD file:
https://github.com/micro-os-plus/sifive-devices-xpack/blob/xpack/xsvd/fe310-xsvd.json
XSVD is basically SVD converted to JSON, so should not be too hard to convert back without too much loss of information.
The Freedom Studio docs mention XSVD files in the Misc subdirectory, but I downloaded it and there are none.

**Comment by justinclift** [comment]
@Fabien-Chouteau Do you remember where the original version of this was sourced from, or did you generate it manually yourself?

Asking because your name is on it as the original author, and we're trying to make sure the licensing is ok for this to be merged: :smile:

&nbsp; https://github.com/AdaCore/svd2ada/commits/master/CMSIS-SVD/SiFive/FE310.svd

**Comment by Fabien-Chouteau** [comment]
Hi @justinclift,

I wrote the file from scratch based on the documentation.

I see that you use Apache License v2.0 which is perfectly fine for me.

Regards,

**Comment by justinclift** [comment]
@posborne Is that workable? :smile:

**Comment by justinclift** [comment]
It looks like SiFive do intend to release SVD files eventually.  Seems unlikely in the short term though, due to other work items being higher priority:

&nbsp; &nbsp; https://forums.sifive.com/t/svd-file-for-e310-g000/731/19

If someone with C++ skills wants it faster though, they could probably submit a PR adding SVD generation  to the SiFive tool devicetree tool:

nbsp; nbsp; https://github.com/sifive/freedom-devicetree-tools/tree/master

**Comment by posborne** [comment]
> @posborne Is that workable? 😄

Sounds reasonable, how does this sound?

1. Rename directory to "SiFive-Community" for files that haven't been provided by the vendor.
2. Add a README.md to the directory containing a brief overview of where these files are sourced from and that these aren't directly provided by SiFive.
3. Add a LICENSE file with the appropriate apache license text applying to the files in this directory.

**Comment by aykevl** [comment]
I have updated the PR with your suggestions.

**Comment by deadprogram** [comment]
I've submitted an alternative SVD file for the SiFive board in PR #85 in part using the feedback from this PR.

**Comment by justinclift** [comment]
Are we ok to kill the tinygo-org:add-fe310 branch?

**Pull request closed without merging**
