### PR TITLE
fixed #31

### LINKED ISSUE #31: AT91SAM9G10 fails because peripheral UHP does not have any registers
adding an if here https://github.com/posborne/cmsis-svd/blob/master/python/cmsis_svd/model.py#L340 fixes this but I'm not sure if this is the right solution. My python skills have been known to suck miserably.

### PR DESCRIPTION
**Pull request by porkybrain**

### CODE REVIEW

**Comment by posborne** [comment]
I think the better solution here is to add `"register_arrays"` to `LIST_TYPE_KEYS`

**Comment by posborne** [comment]
Then it should just return an empty list instead of what it does now.

**Comment by porkybrain** [comment]
I knew there was a better way, I'll update momentarily

**Comment by porkybrain** [comment]
thanks for the tip, that solved the problem.

**Pull request merged**
