### PR TITLE
Added SVDParser.for_mcu class method

### PR DESCRIPTION
**Pull request by KivApple**
See https://github.com/posborne/cmsis-svd/issues/37

### CODE REVIEW

**Comment by KivApple** [comment]
How I should add tests? In separated file or in test_parser.py?
How I should determine availability of SVD files (you said package can be built without SVDs)? Or this is not need for tests?

**Comment by posborne** [comment]
Hi @KivApple,

> How I should add tests? In separated file or in test_parser.py?

I think adding them to test_parser.py is fine to start out.  Later on, we might move things around a little bit, but this is a fine place to start.

> How I should determine availability of SVD files (you said package can be built without SVDs)? Or this is not need for tests (tests always run with SVD files available)?

It is fine to assume that the files will be present wherever the tests are run.  The function should not be expected to work if the svd resources are not packaged with the parser.

**Comment by KivApple** [comment]
I have added two tests for packaged data (first uses SVDParser.for_packaged_xml, second uses SVDParser.for_mcu).

**Comment by posborne** [comment]
Thanks!

**Pull request merged**
