### PR TITLE
Cluster support

### PR DESCRIPTION
**Pull request by stefanhoelzl**
Supports SVDs which declare registers in cluster.
see also https://github.com/posborne/cmsis-svd/issues/47

### CODE REVIEW

**Comment by bradjc** [comment]
Do you think @posborne is coming back?

**Comment by posborne** [comment]
> Do you think @posborne is coming back?

Thanks for the ping; I get a lot of GH notifications so sometimes stuff gets buried (and I was without internet for the past 4 days or so).

Will take a look.

**Comment by bradjc** [comment]
@posborne Cool, thanks! Do you have plans for pushing a new version to https://pypi.org/project/cmsis-svd/ ?

**Comment by bradjc** [comment]
ping

**Pull request merged**
